language: node_js
node_js:
  - 8.13.0
cache:
  directories:
    - node_modules
    - med-inventory/node_modules
install:
  - cd NewsLetter
  - npm install -g firebase-tools
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master